### ISSUE TITLE
website review (assingment 2)

### ISSUE THREAD

**Issue by romizb** [Shirikara/shirikara.github.io#1]
Love your website!
it is very professional, informative, and cozy. we can really see your loving and gentle personality through the layout and design.
I would add a link to Gabor Szabo's web page (https://szabgab.com/), and a link to Weizmann institute (https://www.weizmann.ac.il/pages/), as was instructed in the fist assignment.
Good luck!

P.S
your sour bread looks godly delicious!

**Comment by romizb** [comment]
@liroh99

**Comment by Shirikara** [comment]
Hey Romi @romizb 
Nice to meet you! Thank you for your informative comments about the repository. And thank you for your kind compliment about my homemade bread 🌷 
* I implemented your input and updated the repository according to your insights. 
* As instructed in the assignment 2, please let me know if I can close the issue, or can you close it yourself, maybe? 

See you in the class,
Shiri
