### ISSUE TITLE
A comment for 2nd assignment

### ISSUE THREAD

**Issue by CatalinaDonic** [Shirikara/shirikara.github.io#2]
Hi Shiri,

Your website looks great—I love your style!

I have a small suggestion regarding the LinkedIn and X account links. Placing the icons on the same line as the text might enhance the overall look.

Best regards,
Catalina

@HadarKlimovski

**Comment by Shirikara** [comment]
Hi Catalina,
Nice to meet you and thank you for your comment.
I applied your aesthetics suggestion and aligned the LinkedIn and Tweeter icons to the same line.
Best,
Shiri

**Comment by Shirikara** [comment]
Changes Applied
